---
title: Sentry SDK 导致 Python 出现段异常
created_at: 2018-11-29T14:43:21.767Z
tags:
  - memory
  - Python
  - Sentry
  - Alpine
  - Linux
authors: Frederic Chan
categories: Python
meta:
  keywords: Python memory Sentry Alpine Linux
isPage: false
isFeatured: false
hero:
  image: /images/uploads/python_coroutine_2.png
excerpt: >-
  最近在每课服务器端内存优化的时候更改了 fork() 函数执行的位置，然而修改之后却导致程序在运行时出现段异常。对于 Python
  开发者来说，段异常这类底层的异常并不多见，因此调试过程也值得记录一下。
---




对于 Python 开发者来说，段异常是个很陌生的东西，平常基本不太遇到。最近在给程序调优的时候出现了段异常，导致程序被系统终止然后被 master respawn，然而 respawn 之后很快再次出现问题，一直这样循环。通过 Google 我们可以知道，是内存访问相关的问题。

由于解释器被操作系统终止，因此自然也没有 traceback 输出，因此我们无法从日志中发现问题的起源。幸运的是，Python 3.3 之后我们有了 faulthandler 模块，它可以打印出 trackback 信息。只需要将以下两行代码加入程序中：

{"widget":"qards-code","config":"eyJjb2RlIjoiaW1wb3J0IGZhdWx0aGFuZGxlclxuZmF1bHRoYW5kbGVyLmVuYWJsZSgpIiwibGFuZ3VhZ2UiOiJweXRob24ifQ=="}

于是程序输出了如下信息：

{"widget":"qards-code","config":"eyJjb2RlIjoiRmF0YWwgUHl0aG9uIGVycm9yOiBTZWdtZW50YXRpb24gZmF1bHRcbkN1cnJlbnQgdGhyZWFkIDB4MDAwMDdmZjBmNWNjMWFlOCAobW9zdCByZWNlbnQgY2FsbCBmaXJzdCk6XG5GaWxlIFwiL3Vzci9sb2NhbC9saWIvcHl0aG9uMy43L3NzbC5weVwiLCBsaW5lIDM4OCBpbiBfX25ld19fXG5GaWxlIFwiL3Vzci9sb2NhbC9saWIvcHl0aG9uMy43L3NzbC5weVwiLCBsaW5lIDEyMTEgaW4gd3JhcF9zb2NrZXRcbkZpbGUgXCIvdmFyL2V2ZXJ5Y2xhc3Mtc2VydmVyLy52ZW52L2xpYi9weXRob24zLjcvc2l0ZS1wYWNrYWdlcy9yYXZlbi91dGlscy9odHRwLnB5XCIsIGxpbmUgMzggaW4gY29ubmVjdFxuRmlsZSBcIi91c3IvbG9jYWwvbGliL3B5dGhvbjMuNy9odHRwL2NsaWVudC5weVwiLCBsaW5lIDk1NiBpbiBzZW5kXG5GaWxlIFwiL3Vzci9sb2NhbC9saWIvcHl0aG9uMy43L2h0dHAvY2xpZW50LnB5XCIsIGxpbmUgMTAxNiBpbiBfc2VuZF9vdXRwdXRcbkZpbGUgXCIvdXNyL2xvY2FsL2xpYi9weXRob24zLjcvaHR0cC9jbGllbnQucHlcIiwgbGluZSAxMjI0IGluIGVuZGhlYWRlcnNcbkZpbGUgXCIvdXNyL2xvY2FsL2xpYi9weXRob24zLjcvaHR0cC9jbGllbnQucHlcIiwgbGluZSAxMjc1IGluIF9zZW5kX3JlcXVlc3RcbkZpbGUgXCIvdXNyL2xvY2FsL2xpYi9weXRob24zLjcvaHR0cC9jbGllbnQucHlcIiwgbGluZSAxMjI5IGluIHJlcXVlc3RcbkZpbGUgXCIvdXNyL2xvY2FsL2xpYi9weXRob24zLjcvdXJsbGliL3JlcXVlc3QucHlcIiwgbGluZSAxMzE3IGluIGRvX29wZW5cbkZpbGUgXCIvdmFyL2V2ZXJ5Y2xhc3Mtc2VydmVyLy52ZW52L2xpYi9weXRob24zLjcvc2l0ZS1wYWNrYWdlcy9yYXZlbi91dGlscy9odHRwLnB5XCIsIGxpbmUgNDYgaW4gaHR0cHNfb3BlblxuRmlsZSBcIi91c3IvbG9jYWwvbGliL3B5dGhvbjMuNy91cmxsaWIvcmVxdWVzdC5weVwiLCBsaW5lIDUwMyBpbiBfY2FsbF9jaGFpblxuRmlsZSBcIi91c3IvbG9jYWwvbGliL3B5dGhvbjMuNy91cmxsaWIvcmVxdWVzdC5weVwiLCBsaW5lIDU0MyBpbiBfb3BlblxuRmlsZSBcIi91c3IvbG9jYWwvbGliL3B5dGhvbjMuNy91cmxsaWIvcmVxdWVzdC5weVwiLCBsaW5lIDUyNSBpbiBvcGVuXG5GaWxlIFwiL3Zhci9ldmVyeWNsYXNzLXNlcnZlci8udmVudi9saWIvcHl0aG9uMy43L3NpdGUtcGFja2FnZXMvcmF2ZW4vdXRpbHMvaHR0cC5weVwiLCBsaW5lIDY2IGluIHVybG9wZW5cbkZpbGUgXCIvdmFyL2V2ZXJ5Y2xhc3Mtc2VydmVyLy52ZW52L2xpYi9weXRob24zLjcvc2l0ZS1wYWNrYWdlcy9yYXZlbi90cmFuc3BvcnQvaHR0cC5weVwiLCBsaW5lIDQzIGluIHNlbmRcbkZpbGUgXCIvdmFyL2V2ZXJ5Y2xhc3Mtc2VydmVyLy52ZW52L2xpYi9weXRob24zLjcvc2l0ZS1wYWNrYWdlcy9yYXZlbi90cmFuc3BvcnQvdGhyZWFkZWQucHlcIiwgbGluZSAxNjUgaW4gc2VuZF9zeW5jXG5GaWxlIFwiL3Zhci9ldmVyeWNsYXNzLXNlcnZlci8udmVudi9saWIvcHl0aG9uMy43L3NpdGUtcGFja2FnZXMvcmF2ZW4vdHJhbnNwb3J0L3RocmVhZGVkLnB5XCIsIGxpbmUgMTQ1IGluIF90YXJnZXRcbkZpbGUgXCIvdXNyL2xvY2FsL2xpYi9weXRob24zLjcvdGhyZWFkaW5nLnB5XCIsIGxpbmUgODY1IGluIHJ1blxuRmlsZSBcIi91c3IvbG9jYWwvbGliL3B5dGhvbjMuNy90aHJlYWRpbmcucHlcIiwgbGluZSA5MTcgaW4gX2Jvb3RzdHJhcF9pbm5lclxuRmlsZSBcIi91c3IvbG9jYWwvbGliL3B5dGhvbjMuNy90aHJlYWRpbmcucHlcIiwgbGluZSA4ODUgaW4gX2Jvb3RzdHJhcCJ9"}

于是我们发现问题是有 Sentry 的 SDK（raven）引起的。有没有人有类似的问题呢？Google 了一下之后发现确实有人发生过类似的问题：https://github.com/getsentry/raven-python/issues/1003。底下的回复提到的原因是 Alpine Linux
